// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

using System.Text.Json.Nodes;
using FluentAssertions;
using NomNomzBot.Infrastructure.DevPlatform;

namespace NomNomzBot.Infrastructure.Tests.DevPlatform;

/// <summary>
/// Pins every wire fixture to the Twitch EventSub reference event field tables (the authority; the notification
/// examples on that page are wrong for some events). Paths are dotted, arrays are transparent. A required path
/// counts only when its parent object exists in the fixture: variant objects Twitch does not use are sent as
/// null. See <c>.claude/docs/design/ledgers/eventsub-fixtures-vs-docs.md</c>.
/// </summary>
public sealed class EventSampleFieldCoverageTests
{
    private sealed record EventTable(string[] Required, string[] Optional);

    private static readonly IReadOnlyDictionary<string, EventTable> Tables = new Dictionary<
        string,
        EventTable
    >
    {
        ["chat.cleared"] = new(
            ["broadcaster_user_id", "broadcaster_user_login", "broadcaster_user_name"],
            []
        ),
        ["chat.message"] = new(
            [
                "badges",
                "badges.id",
                "badges.info",
                "badges.set_id",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "chatter_user_id",
                "chatter_user_login",
                "chatter_user_name",
                "cheer.bits",
                "color",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.emote.owner_id",
                "message.fragments.gif.id",
                "message.fragments.gif.url",
                "message.fragments.mention.user_id",
                "message.fragments.mention.user_login",
                "message.fragments.mention.user_name",
                "message.fragments.text",
                "message.fragments.type",
                "message.text",
                "message_id",
                "message_type",
                "reply.parent_message_body",
                "reply.parent_message_id",
                "reply.parent_user_id",
                "reply.parent_user_login",
                "reply.parent_user_name",
                "reply.thread_message_id",
                "reply.thread_user_id",
                "reply.thread_user_login",
                "reply.thread_user_name",
                "source_badges.id",
                "source_badges.info",
                "source_badges.set_id",
            ],
            [
                "channel_points_custom_reward_id",
                "cheer",
                "is_source_only",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
                "message.fragments.emote.format",
                "message.fragments.gif",
                "message.fragments.mention",
                "reply",
                "source_badges",
                "source_broadcaster_user_id",
                "source_broadcaster_user_login",
                "source_broadcaster_user_name",
                "source_message_id",
            ]
        ),
        ["chat.message.deleted"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "message_id",
                "target_user_id",
                "target_user_login",
                "target_user_name",
            ],
            []
        ),
        ["chat.notification"] = new(
            [
                "announcement.color",
                "badges",
                "badges.id",
                "badges.info",
                "badges.set_id",
                "bits_badge_tier.tier",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "charity_donation.amount",
                "charity_donation.amount.currency",
                "charity_donation.amount.decimal_place",
                "charity_donation.charity_name",
                "chatter_is_anonymous",
                "chatter_user_id",
                "chatter_user_name",
                "color",
                "community_sub_gift.id",
                "community_sub_gift.sub_tier",
                "community_sub_gift.total",
                "gift_paid_upgrade.gifter_is_anonymous",
                "gifted_drops_summary.recipient_count",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.emote.owner_id",
                "message.fragments.mention.user_id",
                "message.fragments.mention.user_login",
                "message.fragments.mention.user_name",
                "message.fragments.text",
                "message.fragments.type",
                "message.text",
                "message_id",
                "modiversary.months",
                "notice_type",
                "pay_it_forward.gifter_is_anonymous",
                "prime_paid_upgrade.sub_tier",
                "raid.profile_image_url",
                "raid.user_id",
                "raid.user_login",
                "raid.user_name",
                "raid.viewer_count",
                "resub.cumulative_months",
                "resub.duration_months",
                "resub.is_gift",
                "resub.streak_months",
                "resub.sub_tier",
                "source_badges.id",
                "source_badges.info",
                "source_badges.set_id",
                "sub.duration_months",
                "sub.sub_tier",
                "sub_gift.duration_months",
                "sub_gift.recipient_user_id",
                "sub_gift.recipient_user_login",
                "sub_gift.recipient_user_name",
                "sub_gift.sub_tier",
                "system_message",
                "watch_streak.channel_points_awarded",
                "watch_streak.streak_count",
            ],
            [
                "announcement",
                "bits_badge_tier",
                "charity_donation",
                "charity_donation.amount.value",
                "community_sub_gift",
                "community_sub_gift.cumulative_total",
                "gift_paid_upgrade",
                "gift_paid_upgrade.gifter_user_id",
                "gift_paid_upgrade.gifter_user_name",
                "gifted_drops_summary",
                "is_source_only",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
                "message.fragments.emote.format",
                "message.fragments.mention",
                "modiversary",
                "pay_it_forward",
                "pay_it_forward.gifter_user_id",
                "pay_it_forward.gifter_user_login",
                "pay_it_forward.gifter_user_name",
                "prime_paid_upgrade",
                "raid",
                "resub",
                "resub.gifter_is_anonymous",
                "resub.gifter_user_id",
                "resub.gifter_user_login",
                "resub.gifter_user_name",
                "resub.is_prime",
                "shared_chat_announcement",
                "shared_chat_community_sub_gift",
                "shared_chat_gift_paid_upgrade",
                "shared_chat_gifted_drops_summary",
                "shared_chat_modiversary",
                "shared_chat_pay_it_forward",
                "shared_chat_prime_paid_upgrade",
                "shared_chat_raid",
                "shared_chat_resub",
                "shared_chat_sub",
                "shared_chat_sub_gift",
                "source_badges",
                "source_broadcaster_user_id",
                "source_broadcaster_user_login",
                "source_broadcaster_user_name",
                "source_message_id",
                "sub",
                "sub.is_prime",
                "sub_gift",
                "sub_gift.community_gift_id",
                "sub_gift.cumulative_total",
                "unraid",
                "watch_streak",
            ]
        ),
        ["chat.settings.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "emote_mode",
            ],
            [
                "follower_mode",
                "follower_mode_duration_minutes",
                "slow_mode",
                "slow_mode_wait_time_seconds",
                "subscriber_mode",
                "unique_chat_mode",
            ]
        ),
        ["chat.shared.chat.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "host_broadcaster_user_id",
                "host_broadcaster_user_login",
                "host_broadcaster_user_name",
                "participants",
                "participants.broadcaster_user_id",
                "participants.broadcaster_user_login",
                "participants.broadcaster_user_name",
                "session_id",
            ],
            []
        ),
        ["chat.shared.chat.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "host_broadcaster_user_id",
                "host_broadcaster_user_login",
                "host_broadcaster_user_name",
                "session_id",
            ],
            []
        ),
        ["chat.shared.chat.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "host_broadcaster_user_id",
                "host_broadcaster_user_login",
                "host_broadcaster_user_name",
                "participants",
                "participants.broadcaster_user_id",
                "participants.broadcaster_user_login",
                "participants.broadcaster_user_name",
                "session_id",
            ],
            []
        ),
        ["chat.user.message.held"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.text",
                "message_id",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
            ]
        ),
        ["chat.user.message.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.text",
                "message_id",
                "status",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
            ]
        ),
        ["chat.user.messages.cleared"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "target_user_id",
                "target_user_login",
                "target_user_name",
            ],
            []
        ),
        ["chat.whisper.received"] = new(
            [
                "from_user_id",
                "from_user_login",
                "from_user_name",
                "to_user_id",
                "to_user_login",
                "to_user_name",
                "whisper",
                "whisper.text",
                "whisper_id",
            ],
            []
        ),
        ["community.charity.campaign.progress"] = new(
            [
                "broadcaster_id",
                "broadcaster_login",
                "broadcaster_name",
                "charity_description",
                "charity_logo",
                "charity_name",
                "charity_website",
                "current_amount",
                "current_amount.currency",
                "current_amount.decimal_places",
                "id",
                "target_amount",
                "target_amount.currency",
                "target_amount.decimal_places",
            ],
            ["current_amount.value", "target_amount.value"]
        ),
        ["community.charity.campaign.started"] = new(
            [
                "broadcaster_id",
                "broadcaster_login",
                "broadcaster_name",
                "charity_description",
                "charity_logo",
                "charity_name",
                "charity_website",
                "current_amount",
                "current_amount.currency",
                "current_amount.decimal_places",
                "id",
                "target_amount",
                "target_amount.currency",
                "target_amount.decimal_places",
            ],
            ["current_amount.value", "started_at", "target_amount.value"]
        ),
        ["community.charity.campaign.stopped"] = new(
            [
                "broadcaster_id",
                "broadcaster_login",
                "broadcaster_name",
                "charity_description",
                "charity_logo",
                "charity_name",
                "charity_website",
                "current_amount",
                "current_amount.currency",
                "current_amount.decimal_places",
                "id",
                "target_amount",
                "target_amount.currency",
                "target_amount.decimal_places",
            ],
            ["current_amount.value", "stopped_at", "target_amount.value"]
        ),
        ["community.charity.donation"] = new(
            [
                "amount",
                "amount.currency",
                "amount.decimal_places",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "campaign_id",
                "charity_description",
                "charity_logo",
                "charity_name",
                "charity_website",
                "id",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["amount.value"]
        ),
        ["community.follow"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["followed_at"]
        ),
        ["community.goal.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "description",
                "id",
                "type",
            ],
            ["current_amount", "ended_at", "is_achieved", "started_at", "target_amount"]
        ),
        ["community.goal.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "description",
                "id",
                "type",
            ],
            ["current_amount", "ended_at", "is_achieved", "started_at", "target_amount"]
        ),
        ["community.goal.progress"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "description",
                "id",
                "type",
            ],
            ["current_amount", "ended_at", "is_achieved", "started_at", "target_amount"]
        ),
        ["community.hype.train.began"] = new(
            [
                "all_time_high_level",
                "all_time_high_total",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "goal",
                "id",
                "level",
                "progress",
                "shared_train_participants.broadcaster_user_id",
                "shared_train_participants.broadcaster_user_login",
                "shared_train_participants.broadcaster_user_name",
                "top_contributions",
                "top_contributions.total",
                "top_contributions.type",
                "top_contributions.user_id",
                "top_contributions.user_login",
                "top_contributions.user_name",
                "total",
                "type",
            ],
            ["expires_at", "is_shared_train", "shared_train_participants", "started_at"]
        ),
        ["community.hype.train.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "level",
                "shared_train_participants.broadcaster_user_id",
                "shared_train_participants.broadcaster_user_login",
                "shared_train_participants.broadcaster_user_name",
                "top_contributions",
                "top_contributions.total",
                "top_contributions.type",
                "top_contributions.user_id",
                "top_contributions.user_login",
                "top_contributions.user_name",
                "total",
                "type",
            ],
            [
                "cooldown_ends_at",
                "ended_at",
                "is_shared_train",
                "shared_train_participants",
                "started_at",
            ]
        ),
        ["community.hype.train.progress"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "goal",
                "id",
                "level",
                "progress",
                "shared_train_participants.broadcaster_user_id",
                "shared_train_participants.broadcaster_user_login",
                "shared_train_participants.broadcaster_user_name",
                "top_contributions",
                "top_contributions.total",
                "top_contributions.type",
                "top_contributions.user_id",
                "top_contributions.user_login",
                "top_contributions.user_name",
                "total",
                "type",
            ],
            ["expires_at", "is_shared_train", "shared_train_participants", "started_at"]
        ),
        ["community.poll.began"] = new(
            [
                "bits_voting",
                "bits_voting.amount_per_vote",
                "bits_voting.is_enabled",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "channel_points_voting",
                "channel_points_voting.amount_per_vote",
                "channel_points_voting.is_enabled",
                "choices",
                "choices.bits_votes",
                "choices.channel_points_votes",
                "choices.id",
                "choices.title",
                "choices.votes",
                "ends_at",
                "id",
                "started_at",
                "title",
            ],
            []
        ),
        ["community.poll.ended"] = new(
            [
                "bits_voting",
                "bits_voting.amount_per_vote",
                "bits_voting.is_enabled",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "channel_points_voting",
                "channel_points_voting.amount_per_vote",
                "channel_points_voting.is_enabled",
                "choices",
                "choices.bits_votes",
                "choices.channel_points_votes",
                "choices.id",
                "choices.title",
                "choices.votes",
                "ended_at",
                "id",
                "started_at",
                "status",
                "title",
            ],
            []
        ),
        ["community.poll.progress"] = new(
            [
                "bits_voting",
                "bits_voting.amount_per_vote",
                "bits_voting.is_enabled",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "channel_points_voting",
                "channel_points_voting.amount_per_vote",
                "channel_points_voting.is_enabled",
                "choices",
                "choices.bits_votes",
                "choices.channel_points_votes",
                "choices.id",
                "choices.title",
                "choices.votes",
                "ends_at",
                "id",
                "started_at",
                "title",
            ],
            []
        ),
        ["community.prediction.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "locks_at",
                "outcomes",
                "outcomes.channel_points",
                "outcomes.color",
                "outcomes.id",
                "outcomes.title",
                "outcomes.top_predictors",
                "outcomes.top_predictors.channel_points_used",
                "outcomes.top_predictors.user_id",
                "outcomes.top_predictors.user_login",
                "outcomes.top_predictors.user_name",
                "outcomes.users",
                "started_at",
                "title",
            ],
            ["outcomes.top_predictors.channel_points_won"]
        ),
        ["community.prediction.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "ended_at",
                "id",
                "outcomes",
                "outcomes.channel_points",
                "outcomes.color",
                "outcomes.id",
                "outcomes.title",
                "outcomes.top_predictors",
                "outcomes.top_predictors.channel_points_used",
                "outcomes.top_predictors.user_id",
                "outcomes.top_predictors.user_login",
                "outcomes.top_predictors.user_name",
                "outcomes.users",
                "started_at",
                "status",
                "title",
                "winning_outcome_id",
            ],
            ["outcomes.top_predictors.channel_points_won"]
        ),
        ["community.prediction.locked"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "locked_at",
                "outcomes",
                "outcomes.channel_points",
                "outcomes.color",
                "outcomes.id",
                "outcomes.title",
                "outcomes.top_predictors",
                "outcomes.top_predictors.channel_points_used",
                "outcomes.top_predictors.user_id",
                "outcomes.top_predictors.user_login",
                "outcomes.top_predictors.user_name",
                "outcomes.users",
                "started_at",
                "title",
            ],
            ["outcomes.top_predictors.channel_points_won"]
        ),
        ["community.prediction.progress"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "locks_at",
                "outcomes",
                "outcomes.channel_points",
                "outcomes.color",
                "outcomes.id",
                "outcomes.title",
                "outcomes.top_predictors",
                "outcomes.top_predictors.channel_points_used",
                "outcomes.top_predictors.user_id",
                "outcomes.top_predictors.user_login",
                "outcomes.top_predictors.user_name",
                "outcomes.users",
                "started_at",
                "title",
            ],
            ["outcomes.top_predictors.channel_points_won"]
        ),
        ["identity.user.updated"] = new(
            ["description", "user_id", "user_login", "user_name"],
            ["email", "email_verified"]
        ),
        ["moderation.action.taken"] = new(
            [
                "action",
                "automod_terms.action",
                "automod_terms.from_automod",
                "automod_terms.list",
                "automod_terms.terms",
                "ban.user_id",
                "ban.user_login",
                "ban.user_name",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "delete.message_body",
                "delete.message_id",
                "delete.user_id",
                "delete.user_login",
                "delete.user_name",
                "followers.follow_duration_minutes",
                "mod.user_id",
                "mod.user_login",
                "mod.user_name",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "raid.user_id",
                "raid.user_login",
                "raid.user_name",
                "raid.viewer_count",
                "slow.wait_time_seconds",
                "source_broadcaster_user_id",
                "source_broadcaster_user_login",
                "timeout.expires_at",
                "timeout.user_id",
                "timeout.user_login",
                "timeout.user_name",
                "unban.user_id",
                "unban.user_login",
                "unban.user_name",
                "unban_request.is_approved",
                "unban_request.moderator_message",
                "unban_request.user_id",
                "unban_request.user_login",
                "unban_request.user_name",
                "unmod.user_id",
                "unmod.user_login",
                "unmod.user_name",
                "unraid.user_id",
                "unraid.user_login",
                "unraid.user_name",
                "untimeout.user_id",
                "untimeout.user_login",
                "untimeout.user_name",
                "unvip.user_id",
                "unvip.user_login",
                "unvip.user_name",
                "vip.user_id",
                "vip.user_login",
                "vip.user_name",
                "warn.user_id",
                "warn.user_login",
                "warn.user_name",
            ],
            [
                "automod_terms",
                "ban",
                "ban.reason",
                "delete",
                "followers",
                "mod",
                "raid",
                "shared_chat_ban",
                "shared_chat_delete",
                "shared_chat_timeout",
                "shared_chat_unban",
                "shared_chat_untimeout",
                "slow",
                "source_broadcaster_user_name",
                "timeout",
                "timeout.reason",
                "unban",
                "unban_request",
                "unmod",
                "unraid",
                "untimeout",
                "unvip",
                "vip",
                "warn",
                "warn.chat_rules_cited",
                "warn.reason",
            ]
        ),
        ["moderation.auto.mod.message.held"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "category",
                "level",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.text",
                "message_id",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "held_at",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
            ]
        ),
        ["moderation.auto.mod.message.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "category",
                "level",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.text",
                "message_id",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "status",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "held_at",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
            ]
        ),
        ["moderation.auto.mod.settings.updated"] = new(
            [
                "aggression",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "bullying",
                "disability",
                "misogyny",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "race_ethnicity_or_religion",
                "sex_based_terms",
                "sexuality_sex_or_gender",
                "swearing",
            ],
            ["overall_level"]
        ),
        ["moderation.auto.mod.terms.updated"] = new(
            [
                "action",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "from_automod",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "terms",
            ],
            []
        ),
        ["moderation.moderator.added"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.moderator.removed"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.shield.mode.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_login",
                "moderator_user_name",
            ],
            ["ended_at", "moderator_user_id", "started_at"]
        ),
        ["moderation.shield.mode.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_login",
                "moderator_user_name",
            ],
            ["ended_at", "moderator_user_id", "started_at"]
        ),
        ["moderation.suspicious.user.message"] = new(
            [
                "ban_evasion_evaluation",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "low_trust_status",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.fragments.type",
                "message.message_id",
                "message.text",
                "shared_ban_channel_ids",
                "types",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
            ]
        ),
        ["moderation.suspicious.user.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "low_trust_status",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.unban.request.created"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "text",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["created_at"]
        ),
        ["moderation.unban.request.resolved"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "status",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["moderator_id", "moderator_login", "moderator_name", "resolution_text"]
        ),
        ["moderation.user.banned"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "reason",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["banned_at", "ends_at", "is_permanent"]
        ),
        ["moderation.user.timed.out"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "reason",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["banned_at", "ends_at", "is_permanent"]
        ),
        ["moderation.user.unbanned"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.vip.added"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.vip.removed"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.warning.acknowledged"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["moderation.warning.sent"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["chat_rules_cited", "reason"]
        ),
        ["rewards.automatic.reward.redeemed"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "message.fragments",
                "message.fragments.emote.id",
                "message.fragments.text",
                "message.fragments.type",
                "message.text",
                "reward",
                "reward.channel_points",
                "reward.emote.id",
                "reward.emote.name",
                "reward.type",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["message", "message.fragments.emote", "redeemed_at", "reward.emote"]
        ),
        ["rewards.bits.used"] = new(
            [
                "bits",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "custom_power_up.reward_id",
                "custom_power_up.title",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.emote.owner_id",
                "message.fragments.text",
                "message.fragments.type",
                "message.text",
                "power_up.emote.id",
                "power_up.emote.name",
                "power_up.type",
                "type",
                "user_id",
                "user_login",
                "user_name",
            ],
            [
                "custom_power_up",
                "message",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
                "message.fragments.emote.format",
                "power_up",
                "power_up.emote",
                "power_up.message_effect_id",
            ]
        ),
        ["rewards.cheer"] = new(
            [
                "bits",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "is_anonymous",
                "message",
            ],
            ["user_id", "user_login", "user_name"]
        ),
        ["rewards.custom.power.up.redeemed"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "custom_power_up",
                "custom_power_up.bits",
                "custom_power_up.id",
                "custom_power_up.prompt",
                "custom_power_up.title",
                "id",
                "status",
                "user_id",
                "user_input",
                "user_login",
                "user_name",
            ],
            ["redeemed_at"]
        ),
        ["rewards.gift.subscription"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "is_anonymous",
                "tier",
                "total",
            ],
            ["cumulative_total", "user_id", "user_login", "user_name"]
        ),
        ["rewards.new.subscription"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "is_gift",
                "tier",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["rewards.resubscription"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "cumulative_months",
                "duration_months",
                "message",
                "message.emotes",
                "message.emotes.begin",
                "message.emotes.end",
                "message.emotes.id",
                "message.text",
                "tier",
                "user_id",
                "user_login",
                "user_name",
            ],
            ["streak_months"]
        ),
        ["rewards.reward.created"] = new(
            [
                "background_color",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "cost",
                "default_image",
                "default_image.url_1x",
                "default_image.url_2x",
                "default_image.url_4x",
                "global_cooldown",
                "global_cooldown.is_enabled",
                "global_cooldown.seconds",
                "id",
                "is_enabled",
                "is_in_stock",
                "is_paused",
                "max_per_stream",
                "max_per_stream.is_enabled",
                "max_per_stream.value",
                "max_per_user_per_stream",
                "max_per_user_per_stream.is_enabled",
                "max_per_user_per_stream.value",
                "prompt",
                "title",
            ],
            [
                "cooldown_expires_at",
                "image",
                "image.url_1x",
                "image.url_2x",
                "image.url_4x",
                "is_user_input_required",
                "redemptions_redeemed_current_stream",
                "should_redemptions_skip_request_queue",
            ]
        ),
        ["rewards.reward.redeemed"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "reward",
                "reward.cost",
                "reward.id",
                "reward.prompt",
                "reward.title",
                "status",
                "user_id",
                "user_input",
                "user_login",
                "user_name",
            ],
            ["redeemed_at"]
        ),
        ["rewards.reward.redemption.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "reward",
                "reward.cost",
                "reward.id",
                "reward.prompt",
                "reward.title",
                "status",
                "user_id",
                "user_input",
                "user_login",
                "user_name",
            ],
            ["redeemed_at"]
        ),
        ["rewards.reward.removed"] = new(
            [
                "background_color",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "cost",
                "default_image",
                "default_image.url_1x",
                "default_image.url_2x",
                "default_image.url_4x",
                "global_cooldown",
                "global_cooldown.is_enabled",
                "global_cooldown.seconds",
                "id",
                "is_enabled",
                "is_in_stock",
                "is_paused",
                "max_per_stream",
                "max_per_stream.is_enabled",
                "max_per_stream.value",
                "max_per_user_per_stream",
                "max_per_user_per_stream.is_enabled",
                "max_per_user_per_stream.value",
                "prompt",
                "title",
            ],
            [
                "cooldown_expires_at",
                "image",
                "image.url_1x",
                "image.url_2x",
                "image.url_4x",
                "is_user_input_required",
                "redemptions_redeemed_current_stream",
                "should_redemptions_skip_request_queue",
            ]
        ),
        ["rewards.reward.updated"] = new(
            [
                "background_color",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "cost",
                "default_image",
                "default_image.url_1x",
                "default_image.url_2x",
                "default_image.url_4x",
                "global_cooldown",
                "global_cooldown.is_enabled",
                "global_cooldown.seconds",
                "id",
                "is_enabled",
                "is_in_stock",
                "is_paused",
                "max_per_stream",
                "max_per_stream.is_enabled",
                "max_per_stream.value",
                "max_per_user_per_stream",
                "max_per_user_per_stream.is_enabled",
                "max_per_user_per_stream.value",
                "prompt",
                "title",
            ],
            [
                "cooldown_expires_at",
                "image",
                "image.url_1x",
                "image.url_2x",
                "image.url_4x",
                "is_user_input_required",
                "redemptions_redeemed_current_stream",
                "should_redemptions_skip_request_queue",
            ]
        ),
        ["rewards.subscription.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "is_gift",
                "tier",
                "user_id",
                "user_login",
                "user_name",
            ],
            []
        ),
        ["rewards.watch.streak.received"] = new(
            [
                "announcement.color",
                "badges",
                "badges.id",
                "badges.info",
                "badges.set_id",
                "bits_badge_tier.tier",
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "charity_donation.amount",
                "charity_donation.amount.currency",
                "charity_donation.amount.decimal_place",
                "charity_donation.charity_name",
                "chatter_is_anonymous",
                "chatter_user_id",
                "chatter_user_name",
                "color",
                "community_sub_gift.id",
                "community_sub_gift.sub_tier",
                "community_sub_gift.total",
                "gift_paid_upgrade.gifter_is_anonymous",
                "gifted_drops_summary.recipient_count",
                "message",
                "message.fragments",
                "message.fragments.cheermote.bits",
                "message.fragments.cheermote.tier",
                "message.fragments.emote.emote_set_id",
                "message.fragments.emote.id",
                "message.fragments.emote.owner_id",
                "message.fragments.mention.user_id",
                "message.fragments.mention.user_login",
                "message.fragments.mention.user_name",
                "message.fragments.text",
                "message.fragments.type",
                "message.text",
                "message_id",
                "modiversary.months",
                "notice_type",
                "pay_it_forward.gifter_is_anonymous",
                "prime_paid_upgrade.sub_tier",
                "raid.profile_image_url",
                "raid.user_id",
                "raid.user_login",
                "raid.user_name",
                "raid.viewer_count",
                "resub.cumulative_months",
                "resub.duration_months",
                "resub.is_gift",
                "resub.streak_months",
                "resub.sub_tier",
                "source_badges.id",
                "source_badges.info",
                "source_badges.set_id",
                "sub.duration_months",
                "sub.sub_tier",
                "sub_gift.duration_months",
                "sub_gift.recipient_user_id",
                "sub_gift.recipient_user_login",
                "sub_gift.recipient_user_name",
                "sub_gift.sub_tier",
                "system_message",
                "watch_streak.channel_points_awarded",
                "watch_streak.streak_count",
            ],
            [
                "announcement",
                "bits_badge_tier",
                "charity_donation",
                "charity_donation.amount.value",
                "community_sub_gift",
                "community_sub_gift.cumulative_total",
                "gift_paid_upgrade",
                "gift_paid_upgrade.gifter_user_id",
                "gift_paid_upgrade.gifter_user_name",
                "gifted_drops_summary",
                "is_source_only",
                "message.fragments.cheermote",
                "message.fragments.cheermote.prefix",
                "message.fragments.emote",
                "message.fragments.emote.format",
                "message.fragments.mention",
                "modiversary",
                "pay_it_forward",
                "pay_it_forward.gifter_user_id",
                "pay_it_forward.gifter_user_login",
                "pay_it_forward.gifter_user_name",
                "prime_paid_upgrade",
                "raid",
                "resub",
                "resub.gifter_is_anonymous",
                "resub.gifter_user_id",
                "resub.gifter_user_login",
                "resub.gifter_user_name",
                "resub.is_prime",
                "shared_chat_announcement",
                "shared_chat_community_sub_gift",
                "shared_chat_gift_paid_upgrade",
                "shared_chat_gifted_drops_summary",
                "shared_chat_modiversary",
                "shared_chat_pay_it_forward",
                "shared_chat_prime_paid_upgrade",
                "shared_chat_raid",
                "shared_chat_resub",
                "shared_chat_sub",
                "shared_chat_sub_gift",
                "source_badges",
                "source_broadcaster_user_id",
                "source_broadcaster_user_login",
                "source_broadcaster_user_name",
                "source_message_id",
                "sub",
                "sub.is_prime",
                "sub_gift",
                "sub_gift.community_gift_id",
                "sub_gift.cumulative_total",
                "unraid",
                "watch_streak",
            ]
        ),
        ["stream.ad.break.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "duration_seconds",
                "requester_user_id",
                "requester_user_login",
                "requester_user_name",
            ],
            ["is_automatic", "started_at"]
        ),
        ["stream.channel.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "category_id",
                "category_name",
                "content_classification_labels",
                "language",
                "title",
            ],
            []
        ),
        ["stream.guest.star.guest.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "host_user_id",
                "host_user_login",
                "host_user_name",
                "session_id",
            ],
            [
                "guest_user_id",
                "guest_user_login",
                "guest_user_name",
                "host_audio_enabled",
                "host_video_enabled",
                "host_volume",
                "moderator_user_id",
                "moderator_user_login",
                "moderator_user_name",
                "slot_id",
                "state",
            ]
        ),
        ["stream.guest.star.session.began"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "session_id",
                "started_at",
            ],
            []
        ),
        ["stream.guest.star.session.ended"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "ended_at",
                "host_user_id",
                "host_user_login",
                "host_user_name",
                "session_id",
                "started_at",
            ],
            []
        ),
        ["stream.guest.star.settings.updated"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "is_browser_source_audio_enabled",
                "is_moderator_send_live_enabled",
                "slot_count",
            ],
            ["group_layout"]
        ),
        ["stream.offline"] = new(
            ["broadcaster_user_id", "broadcaster_user_login", "broadcaster_user_name", "id"],
            []
        ),
        ["stream.online"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "id",
                "started_at",
                "type",
            ],
            []
        ),
        ["stream.raid"] = new(
            [
                "from_broadcaster_user_id",
                "from_broadcaster_user_login",
                "from_broadcaster_user_name",
                "to_broadcaster_user_id",
                "to_broadcaster_user_login",
                "to_broadcaster_user_name",
                "viewers",
            ],
            []
        ),
        ["stream.shoutout.received"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "from_broadcaster_user_id",
                "from_broadcaster_user_login",
                "from_broadcaster_user_name",
                "viewer_count",
            ],
            ["started_at"]
        ),
        ["stream.shoutout.sent"] = new(
            [
                "broadcaster_user_id",
                "broadcaster_user_login",
                "broadcaster_user_name",
                "moderator_user_login",
                "moderator_user_name",
                "to_broadcaster_user_id",
                "to_broadcaster_user_login",
                "to_broadcaster_user_name",
                "viewer_count",
            ],
            ["cooldown_ends_at", "moderator_user_id", "started_at", "target_cooldown_ends_at"]
        ),
    };

    [Fact]
    public void Every_fixture_has_a_reference_table()
    {
        Tables
            .Keys.Order()
            .Should()
            .Equal(
                EventSamplePayloads.ByWireName.Keys.Order(),
                "every fixture is checked against its table"
            );
    }

    [Fact]
    public void Fixtures_carry_every_field_the_reference_table_requires()
    {
        List<string> missing = [];
        foreach (KeyValuePair<string, EventTable> entry in Tables)
        {
            Shape shape = ShapeOf(entry.Key);
            missing.AddRange(
                entry
                    .Value.Required.Where(path =>
                        !shape.Paths.Contains(path) && ParentIsObject(shape, path)
                    )
                    .Select(path => $"{entry.Key}: {path}")
            );
        }

        missing
            .Should()
            .BeEmpty("each fixture must carry every field its reference table requires");
    }

    [Fact]
    public void Fixtures_carry_no_field_the_reference_table_lacks()
    {
        List<string> extra = [];
        foreach (KeyValuePair<string, EventTable> entry in Tables)
        {
            HashSet<string> allowed = [.. entry.Value.Required, .. entry.Value.Optional];
            extra.AddRange(
                ShapeOf(entry.Key)
                    .Paths.Where(path => !allowed.Contains(path))
                    .Select(path => $"{entry.Key}: {path}")
            );
        }

        extra
            .Should()
            .BeEmpty("a fixture field the reference table does not define is invented data");
    }

    private sealed record Shape(HashSet<string> Paths, HashSet<string> Objects);

    private static bool ParentIsObject(Shape shape, string path)
    {
        int dot = path.LastIndexOf('.');
        return dot < 0 || shape.Objects.Contains(path[..dot]);
    }

    private static Shape ShapeOf(string wireName)
    {
        JsonNode root = JsonNode.Parse(EventSamplePayloads.ByWireName[wireName])!;
        JsonNode? eventNode =
            root is JsonObject obj && obj.ContainsKey("event") ? obj["event"] : root;
        Shape shape = new([], []);
        Collect(eventNode, "", shape);
        return shape;
    }

    private static void Collect(JsonNode? node, string prefix, Shape shape)
    {
        switch (node)
        {
            case JsonObject obj:
                if (prefix.Length > 0)
                    shape.Objects.Add(prefix);
                foreach (KeyValuePair<string, JsonNode?> property in obj)
                {
                    string path = prefix.Length == 0 ? property.Key : $"{prefix}.{property.Key}";
                    shape.Paths.Add(path);
                    Collect(property.Value, path, shape);
                }
                break;
            case JsonArray items:
                foreach (JsonNode? item in items)
                    Collect(item, prefix, shape);
                break;
        }
    }
}
