// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

namespace NomNomzBot.Application.Abstractions.Templating;

/// <summary>
/// One plain, realistic example value per <see cref="TemplateHelperRegistry"/> key, shown beside the helper
/// in the dashboard's variable picker. These are data values, not prose, so they carry no i18n key.
/// <c>TemplateHelperSampleTests</c> fails for any registry entry that has no sample here.
/// </summary>
internal static class TemplateHelperSamples
{
    private static readonly Dictionary<string, string> ByKey = new(StringComparer.OrdinalIgnoreCase)
    {
        ["channel"] = "kani_dev",
        ["channel.display"] = "Kani_Dev",
        ["channel.id"] = "123456789",
        ["streamer"] = "Kani_Dev",
        ["stream.title"] = "Cozy coding night",
        ["stream.game"] = "Just Chatting",
        ["stream.uptime"] = "2h 15m",
        ["stream.viewers"] = "42",
        ["stream.isLive"] = "true",
        ["stream.startedAt"] = "2026-10-06T18:00:00Z",
        ["tts.audioconnected"] = "true",
        ["status"] = "live",
        ["tense"] = "is",
        ["provider"] = "twitch",
        ["ad.duration"] = "90",
        ["ad.when"] = "5 minutes",
        ["ad.seconds"] = "300",
        ["ad.automatic"] = "true",
        ["poll.title"] = "What next?",
        ["poll.status"] = "completed",
        ["poll.winner"] = "Pizza",
        ["poll.winner.votes"] = "28",
        ["poll.winner.percentage"] = "56",
        ["poll.results"] = "Pizza 28, Pasta 22",
        ["followed_at"] = "2026-10-06T18:30:00Z",
        ["tier"] = "1",
        ["months"] = "12",
        ["streak"] = "6",
        ["message"] = "Great stream!",
        ["also_said"] = "Great stream!",
        ["count"] = "12",
        ["anonymous"] = "false",
        ["bits"] = "100",
        ["gifter"] = "kind_viewer",
        ["gifter.id"] = "987654321",
        ["viewers"] = "25",
        ["reward"] = "Hydrate",
        ["reward.id"] = "a1b2c3d4",
        ["redemption.id"] = "e5f6a7b8",
        ["cost"] = "500",
        ["input"] = "Hello chat",
        ["moderator"] = "mod_jane",
        ["reason"] = "Spam",
        ["duration"] = "600",
        ["broadcaster"] = "Kani_Dev",
        ["title"] = "Cozy coding night",
        ["game"] = "Just Chatting",
        ["viewer.name"] = "kani_dev",
        ["engagement.daysSinceLastSeen"] = "14",
        ["engagement.streak"] = "5",
        ["engagement.months"] = "18",
        ["engagement.years"] = "1",
        ["supporter.name"] = "kind_viewer",
        ["supporter.kind"] = "tip",
        ["supporter.amount"] = "5.00",
        ["supporter.currency"] = "EUR",
        ["supporter.tier"] = "Gold",
        ["supporter.quantity"] = "1",
        ["supporter.message"] = "Keep it up!",
        ["obs.event.<field>"] = "Scene 1",
        ["vts.event.<field>"] = "Model 1",
        ["time"] = "20:15",
        ["time.utc"] = "18:15",
        ["date"] = "2026-10-06",
        ["botname"] = "NomNomzBot",
        ["random.user"] = "kani_dev",
        ["random.number.<n>"] = "7",
        ["random.number.<min>.<max>[.<step>]"] = "42",
        ["roll.<name>.<min>.<max>[.<step>]"] = "13",
        ["roll.<name>"] = "13",
        ["roll.<name>.complement"] = "87",
        ["random.pick.<a.b.c>"] = "b",
        ["count.<key>"] = "12",
        ["list.pick.<name>"] = "Pizza",
        ["custom.<name>.<field>"] = "Blue",
        ["transform.<name>:<text>"] = "HELLO",
        ["args"] = "hello world",
        ["args.<n>"] = "hello",
        ["user"] = "kani_dev",
        ["user.name"] = "kani_dev",
        ["user.id"] = "123456789",
        ["user.provider"] = "twitch",
        ["user.accountAge"] = "3 years",
        ["user.followAge"] = "1 year",
        ["user.pronouns"] = "they/them",
        ["user.messageCount"] = "250",
        ["user.lastmessage"] = "see you tomorrow",
        ["user.link"] = "https://twitch.tv/kani_dev",
        ["viewer.messages"] = "250",
        ["viewer.watchtime"] = "12h",
        ["viewer.firstseen"] = "2025-03-01",
        ["viewer.redemptions"] = "8",
        ["viewer.songrequests"] = "3",
        ["viewer.commands"] = "40",
        ["viewer.days"] = "30",
        ["viewer.avgperday"] = "8",
        ["viewer.botpercent"] = "5",
        ["viewer.data.<key>"] = "Blue",
        ["target"] = "kani_dev",
        ["target.name"] = "kani_dev",
        ["target.displayname"] = "Kani_Dev",
        ["target.known"] = "true",
        ["target.id"] = "123456789",
        ["target.followAge"] = "1 year",
        ["target.lastmessage"] = "see you tomorrow",
        ["target.lastmessage.full"] = "kani_dev: see you tomorrow",
        ["target.randommessage"] = "nice play",
        ["target.link"] = "https://twitch.tv/kani_dev",
        ["target.messages"] = "250",
        ["target.watchtime"] = "12h",
        ["target.firstseen"] = "2025-03-01",
        ["target.redemptions"] = "8",
        ["target.songrequests"] = "3",
        ["target.commands"] = "40",
        ["target.days"] = "30",
        ["target.avgperday"] = "8",
        ["target.botpercent"] = "5",
        ["target.data.<key>"] = "Blue",
        ["name"] = "kani_dev",
        ["link"] = "https://twitch.tv/kani_dev",
        ["subject"] = "they",
        ["object"] = "them",
        ["possessive"] = "their",
        ["presentTense"] = "are",
        ["genderedTerm"] = "person",
        ["user.subject"] = "they",
        ["user.object"] = "them",
        ["user.possessive"] = "their",
        ["user.presentTense"] = "are",
        ["user.genderedTerm"] = "person",
        ["user.tense"] = "are",
        ["target.subject"] = "they",
        ["target.object"] = "them",
        ["target.possessive"] = "their",
        ["target.presentTense"] = "are",
        ["target.genderedTerm"] = "person",
        ["target.tense"] = "are",
        ["verb:<sing|plur>"] = "plays",
        ["user.verb:<sing|plur>"] = "plays",
        ["target.verb:<sing|plur>"] = "plays",
        ["channel.name"] = "kani_dev",
        ["channel.title"] = "Cozy coding night",
        ["channel.game"] = "Just Chatting",
        ["raw.message"] = "!hello world",
        ["playlist_id"] = "37i9dQZF1DX",
        ["track_name"] = "Blinding Lights",
        ["music.favorite.track"] = "Blinding Lights",
        ["music.favorite.artist"] = "The Weeknd",
        ["music.favorite.count"] = "12",
        ["music.favorite.outcome"] = "added",
    };

    /// <summary>The sample for <paramref name="key"/>, or an empty string when none is registered.</summary>
    public static string For(string key) => ByKey.GetValueOrDefault(key, string.Empty);
}
