// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

namespace NomNomzBot.Application.Identity.Services;

/// <summary>
/// One pronoun as published by the alejo.io pronoun API
/// (<c>GET https://api.pronouns.alejo.io/v1/pronouns</c>) — the same source the Twitch pronoun
/// chat plugins read. <see cref="Subject"/>/<see cref="Object"/> carry the API's display casing
/// (e.g. <c>They</c>/<c>Them</c>); <see cref="Singular"/> is the API's grammatical-number flag.
/// </summary>
public sealed record PronounRecord(string Subject, string Object, bool Singular);

/// <summary>
/// Fetches the canonical pronoun reference set from the alejo.io pronoun API so the seeded list
/// stays current with the upstream source the Twitch ecosystem uses. The endpoint lists only the
/// base pronouns — combinations (he/they, she/they, he/she) are generated by alejo from pronoun
/// pairs and are NOT returned here, so the caller keeps those in its bundled set.
/// </summary>
public interface IAlejoPronounClient
{
    /// <summary>
    /// GETs the v1 pronoun endpoint and maps the id-keyed object into pronoun records. Best-effort:
    /// returns <c>null</c> on any transport, status, or parse failure (it never throws), and an
    /// empty list if the endpoint returns no usable rows — the caller treats both as "use the
    /// bundled fallback".
    /// </summary>
    Task<IReadOnlyList<PronounRecord>?> FetchAsync(CancellationToken ct = default);
}
