// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

package bot.nomnomz.dashboard.core.network

import java.io.File
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.elementNames
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject

// Keeps the hand-written typed DTOs in lock-step with the backend without anyone eyeballing every change.
//
// The backend is the single source of truth: it emits an OpenAPI document describing every DTO. The
// committed snapshot (server/openapi/v1.json) is regenerated by the backend OpenApiSpecSnapshotTest, so a C#
// DTO change always lands as a spec diff. This test then asserts that every typed Kotlin DTO's *serialized*
// field names (via the kotlinx.serialization descriptor — the exact names that go on the wire) still exist on
// the matching backend schema.
//
// Direction of the guard:
//   - A field on the Kotlin DTO that is NOT on the backend schema FAILS — that is real drift (the backend
//     renamed or removed it), and the Kotlin field would now silently deserialize to its default. This is the
//     dangerous, invisible bug the test exists to catch.
//   - A field on the backend schema that the Kotlin DTO omits is allowed — the client deliberately reads a
//     subset (ApiClient's Json ignores unknown keys), so adding a backend field never breaks the build.
//
// Add a line to [contracts] whenever you introduce a typed response DTO; it is then guarded forever.
class ApiContractTest {

    private val contracts: List<Pair<KSerializer<*>, String>> =
        listOf(
            BotStatus.serializer() to "BotStatusDto",
            LoginProvider.serializer() to "LoginProviderDto",
            CurrentUser.serializer() to "CurrentUserDto",
            DashboardStats.serializer() to "DashboardStatsDto",
            DeviceCodeStart.serializer() to "DeviceCodeStartDto",
            DeviceLoginPoll.serializer() to "DeviceLoginPollDto",
            DeviceBotPoll.serializer() to "DeviceBotPollDto",
            IntegrationStatus.serializer() to "IntegrationStatusDto",
            OAuthStart.serializer() to "OAuthStartDto",
            SystemChecks.serializer() to "SystemChecks",
            SystemStatus.serializer() to "SystemStatusDto",
            SetupStep.serializer() to "SetupStepDto",
            SetupField.serializer() to "SetupFieldDto",
            SetupWizard.serializer() to "SetupWizardDto",
            SetupAction.serializer() to "SetupActionDto",
            CommunityMember.serializer() to "CommunityUserDto",
            CommandSummary.serializer() to "CommandDto",
            TimerSummary.serializer() to "TimerListItem",
            TimerDetail.serializer() to "TimerDto",
            BannedUser.serializer() to "BannedUserDto",
            MissingScopes.serializer() to "MissingScopesDto",
            MissingScope.serializer() to "MissingScopeDto",
            ScopeRegrantStart.serializer() to "ScopeRegrantStartDto",
            StreamInfo.serializer() to "StreamInfoDto",
            LeaderboardEntry.serializer() to "LeaderboardEntryDto",
            AlertSummary.serializer() to "EventResponseListItem",
            AlertDetail.serializer() to "EventResponseDto",
            EventResponsePreset.serializer() to "EventResponsePresetDto",
            PipelineActionDescriptor.serializer() to "PipelineActionDescriptorDto",
            PipelineConditionDescriptor.serializer() to "PipelineConditionDescriptorDto",
            PipelineCatalogueRemote.serializer() to "PipelineCatalogueDto",
            CreateInboundBody.serializer() to "CreateInboundWebhookRequest",
            WidgetSummary.serializer() to "WidgetDetail",
            CreateWidgetBody.serializer() to "CreateWidgetRequest",
            UpdateWidgetBody.serializer() to "UpdateWidgetRequest",
            CompileWidgetBody.serializer() to "CompileWidgetRequest",
            CloneWidgetBody.serializer() to "CloneWidgetRequest",
            WidgetTemplate.serializer() to "WidgetTemplate",
            WidgetVersionSummary.serializer() to "WidgetVersionSummary",
            WidgetVersionDetail.serializer() to "WidgetVersionDetail",
            ProjectDto.serializer() to "ProjectDto",
            ProjectManifestDto.serializer() to "ProjectManifestDto",
            GalleryItemSummary.serializer() to "GalleryItemSummary",
            GalleryItemDetail.serializer() to "GalleryItemDetail",
            CustomDataSourceOption.serializer() to "CustomDataSourceOptionDto",
            RewardSummary.serializer() to "RewardDetail",
            RedemptionSummary.serializer() to "RedemptionListItem",
            RedemptionTimer.serializer() to "RedemptionTimerDto",
            CreateRewardBody.serializer() to "CreateRewardRequest",
            UpdateRewardBody.serializer() to "UpdateRewardRequest",
            // NOTE: LiveGameCatalogEntryDto is intentionally NOT guarded here — the catalog endpoint returns an
            // untyped IActionResult, so the OpenAPI generator never emits that schema (there is nothing to match
            // against). The Kotlin DTO mirrors the C# record by hand; a backend follow-up should add a
            // ProducesResponseType<StatusResponseDto<IReadOnlyList<LiveGameCatalogEntryDto>>> so it can be guarded.
            GameSession.serializer() to "GameSessionDto",
            StartLiveGameBody.serializer() to "StartLiveGameRequest",
            CurrencyAccountSummary.serializer() to "CurrencyAccountDto",
            EarningRule.serializer() to "EarningRuleDto",
            CatalogItem.serializer() to "CatalogItemDto",
            ModLogEntry.serializer() to "ModLogEntryDto",
            AutomodConfig.serializer() to "AutomodConfigDto",
            AutomodLinkFilter.serializer() to "AutomodLinkFilterDto",
            AutomodCapsFilter.serializer() to "AutomodCapsFilterDto",
            AutomodBannedPhrases.serializer() to "AutomodBannedPhrasesDto",
            AutomodEmoteSpam.serializer() to "AutomodEmoteSpamDto",
            ModerationRule.serializer() to "ModerationRuleDetail",
            UserModerationContext.serializer() to "UserModerationContextDto",
            ModerationActionLog.serializer() to "ModerationActionLog",
            ModerationActionResult.serializer() to "ModerationActionResult",
            UnbanRequest.serializer() to "UnbanRequestDto",
            ViewerReport.serializer() to "ViewerReportDto",
            ResolveReportBody.serializer() to "ResolveViewerReportRequest",
            UserNote.serializer() to "UserNoteDto",
            CreateNoteBody.serializer() to "CreateUserNoteRequest",
            UpdateNoteBody.serializer() to "UpdateUserNoteRequest",
            UserModerationHistorySummary.serializer() to "UserModerationHistorySummaryDto",
            UserTrustSummary.serializer() to "UserTrustSummaryDto",
            ModerationStanding.serializer() to "ModerationStandingDto",
            SetModerationStandingBody.serializer() to "SetModerationStandingRequest",
            EscalationLadderStep.serializer() to "EscalationLadderStep",
            EscalationPolicy.serializer() to "ModerationEscalationPolicyDto",
            UpsertEscalationPolicyBody.serializer() to "UpsertEscalationPolicyRequest",
            NetworkNukeBatch.serializer() to "NetworkNukeBatchDto",
            NetworkNukeBody.serializer() to "NetworkNukeRequest",
            SharedBanTrustedChannel.serializer() to "SharedBanTrustedChannelDto",
            SharedBanSettings.serializer() to "SharedBanSettingsDto",
            SaveSharedBanSettingsBody.serializer() to "SaveSharedBanSettingsRequest",
            AddTrustedChannelBody.serializer() to "AddTrustedChannelRequest",
            TtsVoice.serializer() to "TtsVoiceDto",
            UserTtsVoice.serializer() to "UserTtsVoiceDto",
            SetUserVoiceBody.serializer() to "SetUserVoiceDto",
            TtsConfig.serializer() to "TtsConfigDto",
            TtsVoicePage.serializer() to "PaginatedResponseOfTtsVoiceDto",
            SetTtsByokKeyBody.serializer() to "SetTtsByokKeyDto",
            TtsQueueEntry.serializer() to "TtsQueueEntryDto",
            TtsLexiconEntry.serializer() to "TtsLexiconEntryDto",
            UpsertTtsLexiconEntryBody.serializer() to "UpsertTtsLexiconEntryDto",
            BlockedTrack.serializer() to "BlockedTrackDto",
            BlockedTrackPage.serializer() to "PaginatedResponseOfBlockedTrackDto",
            BlockTrackBody.serializer() to "BlockTrackRequest",
            ChatPoll.serializer() to "ChatPollDto",
            ChatPollOption.serializer() to "ChatPollOptionDto",
            OpenChatPollRequest.serializer() to "OpenChatPollRequest",
            UserStats.serializer() to "UserStatsDto",
            CurrencyLedgerEntry.serializer() to "CurrencyLedgerEntryDto",
            BillingSubscription.serializer() to "SubscriptionDto",
            BillingTier.serializer() to "TierDto",
            BillingTierLimit.serializer() to "TierLimitDto",
            BillingEntitlement.serializer() to "EntitlementDto",
            BillingUsageMetric.serializer() to "UsageMetricDto",
            BillingInvoice.serializer() to "InvoiceDto",
            CheckoutSession.serializer() to "CheckoutSessionDto",
            BillingPortal.serializer() to "BillingPortalDto",
            FoundersBadge.serializer() to "FoundersBadgeDto",
            InviteCodeValidation.serializer() to "InviteCodeValidationDto",
            InviteRedeemResult.serializer() to "RedeemInviteCodeResultDto",
            ChatMessage.serializer() to "DashboardChatMessageDto",
            ChatEmoteCatalogue.serializer() to "ChatEmoteCatalogueDto",
            BanUserBody.serializer() to "BanUserRequest",
            FileReportBody.serializer() to "FileViewerReportRequest",
            UnbanUserBody.serializer() to "UnbanUserRequest",
            NetworkBanResult.serializer() to "NetworkBanResultDto",
            ChannelBanOutcome.serializer() to "ChannelBanOutcomeDto",
            ResolvedAccess.serializer() to "ResolvedAccessDto",
            PickList.serializer() to "PickListDto",
            PickListPreview.serializer() to "PickListPreviewDto",
            CreatePickListBody.serializer() to "CreatePickListRequest",
            UpdatePickListBody.serializer() to "UpdatePickListRequest",
            ChatTrigger.serializer() to "ChatTriggerDto",
            CreateChatTriggerBody.serializer() to "CreateChatTriggerRequest",
            UpdateChatTriggerBody.serializer() to "UpdateChatTriggerRequest",
            Giveaway.serializer() to "GiveawayDto",
            UpsertGiveawayBody.serializer() to "UpsertGiveawayRequest",
            GiveawayWinner.serializer() to "GiveawayWinnerDto",
            CodePool.serializer() to "CodePoolDto",
            CodePoolDetail.serializer() to "CodePoolDetailDto",
            MaskedCode.serializer() to "MaskedCodeDto",
            CreateCodePoolBody.serializer() to "CreateCodePoolRequest",
            AddCodesBody.serializer() to "AddCodesRequest",
            CodeInput.serializer() to "CodeInput",
            SupporterConnection.serializer() to "SupporterConnectionDto",
            UpsertSupporterConnectionBody.serializer() to "UpsertSupporterConnectionRequest",
            SupporterEvent.serializer() to "SupporterEventDto",
            ChannelPersonality.serializer() to "ChannelPersonalityDto",
            SetPersonalityBody.serializer() to "SetChannelPersonalityRequest",
            EngagementConfig.serializer() to "EngagementConfigDto",
            UpdateEngagementConfigBody.serializer() to "UpdateEngagementConfigRequest",
            SetViewerDatumBody.serializer() to "SetViewerDatumRequest",
            FeatureStatus.serializer() to "FeatureStatusDto",
            DiscordGuildInfo.serializer() to "DiscordGuildInfoDto",
            DiscordGuildRole.serializer() to "DiscordGuildRoleDto",
            DiscordGuildChannel.serializer() to "DiscordGuildChannelDto",
            DiscordNotificationRole.serializer() to "DiscordNotificationRoleDto",
            CreateDiscordRoleBody.serializer() to "CreateDiscordNotificationRoleRequest",
            UpdateDiscordRoleBody.serializer() to "UpdateDiscordNotificationRoleRequest",
            StreamerEnabledBody.serializer() to "StreamerEnabledRequest",
            LiveOpsMarker.serializer() to "TwitchStreamMarker",
            CreateMarkerBody.serializer() to "CreateMarkerDto",
            LiveOpsSchedule.serializer() to "TwitchSchedule",
            LiveOpsScheduleSegment.serializer() to "TwitchScheduleSegment",
            LiveOpsScheduleCategory.serializer() to "TwitchScheduleCategory",
            LiveOpsScheduleVacation.serializer() to "TwitchScheduleVacation",
            CreateScheduleSegmentBody.serializer() to "CreateScheduleSegmentRequest",
            UpdateScheduleSegmentBody.serializer() to "UpdateScheduleSegmentRequest",
            UpdateScheduleSettingsBody.serializer() to "UpdateScheduleSettingsDto",
            // Platform-admin (Plane-C): live status hub + IAM + tenant ops + audit response DTOs.
            AdminStats.serializer() to "AdminStatsDto",
            AdminSystem.serializer() to "AdminSystemDto",
            AdminServiceHealth.serializer() to "ServiceHealthDto",
            IamRole.serializer() to "IamRoleDto",
            IamPrincipalSummary.serializer() to "IamPrincipalSummaryDto",
            IamRoleAssignment.serializer() to "IamRoleAssignmentDto",
            IamPrincipal.serializer() to "IamPrincipalDto",
            AdminTenant.serializer() to "AdminTenantDto",
            AdminTenantDetail.serializer() to "AdminTenantDetailDto",
            TenantAccessGrant.serializer() to "TenantAccessGrantDto",
            IamAuditEntry.serializer() to "IamAuditEntryDto",
            // OBS control (obs-control.md §4/§5): connection config + bridge + live state/scene/input DTOs and
            // the control request bodies.
            ObsConnection.serializer() to "ObsConnectionDto",
            UpsertObsConnectionBody.serializer() to "UpsertObsConnectionRequest",
            ObsBridgeSetup.serializer() to "ObsBridgeSetupDto",
            ObsBridgeStatus.serializer() to "ObsBridgeStatusDto",
            ObsState.serializer() to "ObsStateDto",
            ObsScene.serializer() to "ObsSceneDto",
            ObsInput.serializer() to "ObsInputDto",
            ObsSceneBody.serializer() to "ObsSceneRequest",
            ObsToggleBody.serializer() to "ObsToggleRequest",
            ObsRecordBody.serializer() to "ObsRecordRequest",
            // VTube Studio (vtube-studio.md §4): connection config + inventory DTOs and the control request bodies.
            VtsConnection.serializer() to "VtsConnectionDto",
            UpsertVtsConnectionBody.serializer() to "UpsertVtsConnectionRequest",
            VtsModelInventory.serializer() to "VtsModelInventory",
            VtsModelRef.serializer() to "VtsModelRef",
            VtsHotkeyRef.serializer() to "VtsHotkeyRef",
            VtsControlBody.serializer() to "VtsControlRequest",
            VtsRequestResult.serializer() to "VtsRequestResult",
            // Automation API tokens + device pairing (automation-api.md §5 + stream-deck.md).
            AutomationToken.serializer() to "AutomationTokenDto",
            IssuedAutomationToken.serializer() to "IssuedAutomationTokenDto",
            CreateAutomationTokenBody.serializer() to "CreateAutomationTokenRequest",
            PairingCode.serializer() to "PairingCodeDto",
            MintPairingCodeBody.serializer() to "MintPairingCodeRequest",
            // Widget gallery — community submit + reviewer queue (widgets-overlays.md §5c). GalleryItemSummary /
            // GalleryItemDetail are registered above; these are the new request bodies.
            SubmitGalleryItemBody.serializer() to "SubmitGalleryItemRequest",
            ReviewGalleryItemBody.serializer() to "ReviewGalleryItemRequest",
            PinGalleryItemBody.serializer() to "UpdatePinRequest",
            // My data (GDPR self-service). RequestErasureBody is a deliberate one-field subset with no matching
            // named schema, so it is intentionally NOT registered.
            DataExport.serializer() to "DataExportDto",
            ErasureRequest.serializer() to "ErasureRequestDto",
            ConsentRecord.serializer() to "ConsentRecordDto",
            GrantConsentBody.serializer() to "GrantConsentRequest",
            // Media Share (viewer clip queue).
            MediaShareRequest.serializer() to "MediaShareRequestDto",
            MediaShareConfig.serializer() to "MediaShareConfigDto",
            UpdateMediaShareConfigBody.serializer() to "UpdateMediaShareConfigRequest",
            ReorderMediaBody.serializer() to "ReorderMediaRequest",
            // Bundles + marketplace. The inspect/import/installed/publish RESPONSES are untyped objects on the
            // backend (no named schema), so only the request bodies + the marketplace item DTO are registered.
            ExportItemRef.serializer() to "ExportItemRef",
            BundleMetadataBody.serializer() to "BundleMetadata",
            ExportBody.serializer() to "ExportRequest",
            MarketplaceItem.serializer() to "MarketplaceItemDto",
            MarketplaceInstallBody.serializer() to "MarketplaceInstallRequest",
            PublisherTokenBody.serializer() to "MarketplacePublisherTokenRequest",
            // Assets (overlay/widget media library).
            ChannelAsset.serializer() to "ChannelAssetDto",
        )

    @Test
    fun typed_dtos_have_no_fields_absent_from_the_backend_contract() {
        val schemas = loadSchemas()
        val problems: MutableList<String> = mutableListOf()

        for ((serializer, schemaName) in contracts) {
            val schema = schemas[schemaName]?.jsonObject
            if (schema == null) {
                problems += "$schemaName: no such schema in the OpenAPI document"
                continue
            }

            val specProps: Set<String> = schema["properties"]?.jsonObject?.keys.orEmpty()
            val dtoFields: Set<String> = serializer.descriptor.elementNames.toSet()
            val onlyInDto: Set<String> = dtoFields - specProps

            if (onlyInDto.isNotEmpty()) {
                problems +=
                    "$schemaName: DTO declares ${onlyInDto.sorted()} which the backend schema " +
                        "(${specProps.sorted()}) does not — renamed/removed on the backend?"
            }
        }

        if (problems.isNotEmpty()) {
            fail(
                "Frontend DTOs have drifted from the backend OpenAPI contract:\n" +
                    problems.joinToString("\n") { "  • $it" } +
                    "\n\nRegenerate server/openapi/v1.json (OpenApiSpecSnapshotTest) and reconcile the DTOs."
            )
        }
    }

    private fun loadSchemas() =
        Json.parseToJsonElement(specFile().readText())
            .jsonObject["components"]!!
            .jsonObject["schemas"]!!
            .jsonObject

    /** Walk up from the test working directory to the committed spec, so the test is location-independent. */
    private fun specFile(): File {
        var dir: File? = File(System.getProperty("user.dir"))
        while (dir != null) {
            val candidate = File(dir, "server/openapi/v1.json")
            if (candidate.exists()) return candidate
            dir = dir.parentFile
        }
        fail("Could not locate server/openapi/v1.json from ${System.getProperty("user.dir")}")
    }
}
