// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

package bot.nomnomz.dashboard.core.network

import java.io.File
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.elementNames
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject

// Keeps the hand-written typed DTOs in lock-step with the backend without anyone eyeballing every change.
//
// The backend is the single source of truth: it emits an OpenAPI document describing every DTO. The
// committed snapshot (server/openapi/v1.json) is regenerated by the backend OpenApiSpecSnapshotTest, so a C#
// DTO change always lands as a spec diff. This test then asserts that every typed Kotlin DTO's *serialized*
// field names (via the kotlinx.serialization descriptor — the exact names that go on the wire) still exist on
// the matching backend schema.
//
// Direction of the guard:
//   - A field on the Kotlin DTO that is NOT on the backend schema FAILS — that is real drift (the backend
//     renamed or removed it), and the Kotlin field would now silently deserialize to its default. This is the
//     dangerous, invisible bug the test exists to catch.
//   - A field on the backend schema that the Kotlin DTO omits is allowed — the client deliberately reads a
//     subset (ApiClient's Json ignores unknown keys), so adding a backend field never breaks the build.
//
// Add a line to [contracts] whenever you introduce a typed response DTO; it is then guarded forever.
class ApiContractTest {

    private val contracts: List<Pair<KSerializer<*>, String>> =
        listOf(
            BotStatus.serializer() to "BotStatusDto",
            LoginProvider.serializer() to "LoginProviderDto",
            CurrentUser.serializer() to "CurrentUserDto",
            DashboardStats.serializer() to "DashboardStatsDto",
            DeviceCodeStart.serializer() to "DeviceCodeStartDto",
            DeviceLoginPoll.serializer() to "DeviceLoginPollDto",
            DeviceBotPoll.serializer() to "DeviceBotPollDto",
            IntegrationStatus.serializer() to "IntegrationStatusDto",
            OAuthStart.serializer() to "OAuthStartDto",
            SystemChecks.serializer() to "SystemChecks",
            SystemStatus.serializer() to "SystemStatusDto",
            SetupStep.serializer() to "SetupStepDto",
            SetupField.serializer() to "SetupFieldDto",
            SetupWizard.serializer() to "SetupWizardDto",
            SetupAction.serializer() to "SetupActionDto",
            CommunityMember.serializer() to "CommunityUserDto",
            CommandSummary.serializer() to "CommandDto",
            TimerSummary.serializer() to "TimerListItem",
            TimerDetail.serializer() to "TimerDto",
            BannedUser.serializer() to "BannedUserDto",
            MissingScopes.serializer() to "MissingScopesDto",
            MissingScope.serializer() to "MissingScopeDto",
            ScopeRegrantStart.serializer() to "ScopeRegrantStartDto",
            StreamInfo.serializer() to "StreamInfoDto",
            LeaderboardEntry.serializer() to "LeaderboardEntryDto",
            AlertSummary.serializer() to "EventResponseListItem",
            AlertDetail.serializer() to "EventResponseDto",
            WidgetSummary.serializer() to "WidgetDetail",
            RewardSummary.serializer() to "RewardDetail",
            RedemptionSummary.serializer() to "RedemptionListItem",
            CurrencyAccountSummary.serializer() to "CurrencyAccountDto",
            EarningRule.serializer() to "EarningRuleDto",
            CatalogItem.serializer() to "CatalogItemDto",
            ModLogEntry.serializer() to "ModLogEntryDto",
            AutomodConfig.serializer() to "AutomodConfigDto",
            AutomodLinkFilter.serializer() to "AutomodLinkFilterDto",
            AutomodCapsFilter.serializer() to "AutomodCapsFilterDto",
            AutomodBannedPhrases.serializer() to "AutomodBannedPhrasesDto",
            AutomodEmoteSpam.serializer() to "AutomodEmoteSpamDto",
            ModerationRule.serializer() to "ModerationRuleDetail",
            UserModerationContext.serializer() to "UserModerationContextDto",
            ModerationActionLog.serializer() to "ModerationActionLog",
            TtsVoice.serializer() to "TtsVoiceDto",
            TtsConfig.serializer() to "TtsConfigDto",
            TtsQueueEntry.serializer() to "TtsQueueEntryDto",
            UserStats.serializer() to "UserStatsDto",
            CurrencyLedgerEntry.serializer() to "CurrencyLedgerEntryDto",
            BillingSubscription.serializer() to "SubscriptionDto",
            BillingTier.serializer() to "TierDto",
            BillingTierLimit.serializer() to "TierLimitDto",
            BillingEntitlement.serializer() to "EntitlementDto",
            BillingUsageMetric.serializer() to "UsageMetricDto",
            BillingInvoice.serializer() to "InvoiceDto",
            CheckoutSession.serializer() to "CheckoutSessionDto",
            BillingPortal.serializer() to "BillingPortalDto",
            FoundersBadge.serializer() to "FoundersBadgeDto",
            InviteCodeValidation.serializer() to "InviteCodeValidationDto",
            InviteRedeemResult.serializer() to "RedeemInviteCodeResultDto",
            ChatMessage.serializer() to "DashboardChatMessageDto",
            ChatEmoteCatalogue.serializer() to "ChatEmoteCatalogueDto",
            BanUserBody.serializer() to "BanUserRequest",
            NetworkBanResult.serializer() to "NetworkBanResultDto",
            ChannelBanOutcome.serializer() to "ChannelBanOutcomeDto",
            ResolvedAccess.serializer() to "ResolvedAccessDto",
            PickList.serializer() to "PickListDto",
            CreatePickListBody.serializer() to "CreatePickListRequest",
            UpdatePickListBody.serializer() to "UpdatePickListRequest",
            Giveaway.serializer() to "GiveawayDto",
            UpsertGiveawayBody.serializer() to "UpsertGiveawayRequest",
            GiveawayWinner.serializer() to "GiveawayWinnerDto",
            CodePool.serializer() to "CodePoolDto",
            CodePoolDetail.serializer() to "CodePoolDetailDto",
            MaskedCode.serializer() to "MaskedCodeDto",
            CreateCodePoolBody.serializer() to "CreateCodePoolRequest",
            AddCodesBody.serializer() to "AddCodesRequest",
            CodeInput.serializer() to "CodeInput",
            SupporterConnection.serializer() to "SupporterConnectionDto",
            UpsertSupporterConnectionBody.serializer() to "UpsertSupporterConnectionRequest",
            SupporterEvent.serializer() to "SupporterEventDto",
            ChannelPersonality.serializer() to "ChannelPersonalityDto",
            SetPersonalityBody.serializer() to "SetChannelPersonalityRequest",
            EngagementConfig.serializer() to "EngagementConfigDto",
            UpdateEngagementConfigBody.serializer() to "UpdateEngagementConfigRequest",
            SetViewerDatumBody.serializer() to "SetViewerDatumRequest",
            FeatureStatus.serializer() to "FeatureStatusDto",
        )

    @Test
    fun typed_dtos_have_no_fields_absent_from_the_backend_contract() {
        val schemas = loadSchemas()
        val problems: MutableList<String> = mutableListOf()

        for ((serializer, schemaName) in contracts) {
            val schema = schemas[schemaName]?.jsonObject
            if (schema == null) {
                problems += "$schemaName: no such schema in the OpenAPI document"
                continue
            }

            val specProps: Set<String> = schema["properties"]?.jsonObject?.keys.orEmpty()
            val dtoFields: Set<String> = serializer.descriptor.elementNames.toSet()
            val onlyInDto: Set<String> = dtoFields - specProps

            if (onlyInDto.isNotEmpty()) {
                problems +=
                    "$schemaName: DTO declares ${onlyInDto.sorted()} which the backend schema " +
                        "(${specProps.sorted()}) does not — renamed/removed on the backend?"
            }
        }

        if (problems.isNotEmpty()) {
            fail(
                "Frontend DTOs have drifted from the backend OpenAPI contract:\n" +
                    problems.joinToString("\n") { "  • $it" } +
                    "\n\nRegenerate server/openapi/v1.json (OpenApiSpecSnapshotTest) and reconcile the DTOs."
            )
        }
    }

    private fun loadSchemas() =
        Json.parseToJsonElement(specFile().readText())
            .jsonObject["components"]!!
            .jsonObject["schemas"]!!
            .jsonObject

    /** Walk up from the test working directory to the committed spec, so the test is location-independent. */
    private fun specFile(): File {
        var dir: File? = File(System.getProperty("user.dir"))
        while (dir != null) {
            val candidate = File(dir, "server/openapi/v1.json")
            if (candidate.exists()) return candidate
            dir = dir.parentFile
        }
        fail("Could not locate server/openapi/v1.json from ${System.getProperty("user.dir")}")
    }
}
