// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Labs.
//
//  This file is part of NomNomzBot, free software licensed under the GNU Affero
//  General Public License v3.0 or later. You may redistribute and/or modify it
//  under those terms. Distributed WITHOUT ANY WARRANTY. See LICENSE for details.
//
//  SPDX-License-Identifier: AGPL-3.0-or-later
// -----------------------------------------------------------------------------

using NomNomzBot.Application.Raids;

namespace NomNomzBot.Infrastructure.Tests.Stream.RaidSuggestions;

/// <summary>
/// One streamer's raid-scoring rules (the legacy bot's numbers), built as test data. The same
/// object lives as JSON in the results notes; production code carries no rule of its own.
/// </summary>
internal static class StoneyRaidRules
{
    public static readonly RaidScoringRules Rules = new(
        PreferredCategories:
        [
            new RaidCategoryRule("Software and Game Development", 60, "Software cat"),
            new RaidCategoryRule("Science & Technology", 40, "Sci&Tech cat"),
        ],
        OtherCategoryWeight: -20,
        OtherCategoryLabel: "non-dev cat",
        Keywords:
        [
            new RaidKeywordRule(
                "gamedev signal",
                -40,
                [
                    "gamedev",
                    "gamedevelopment",
                    "indiedev",
                    "indiegamedev",
                    "gamejam",
                    "godot",
                    "unity",
                    "unrealengine",
                    "unreal",
                    "gamemaker",
                    "gamemakerstudio",
                    "construct",
                    "construct2",
                    "construct3",
                    "defold",
                    "lovd2",
                    "pygame",
                    "phaser",
                    "raylib",
                    "monogame",
                    "pixijs",
                    "playcanvas",
                    "roguelike",
                    "roguelite",
                    "deckbuilder",
                    "cardgame",
                    "metroidvania",
                    "platformer",
                    "shmup",
                    "bullethell",
                    "fightinggame",
                    "jrpg",
                    "arpg",
                    "crpg",
                    "wrpg",
                    "rpgmaker",
                    "survivalgame",
                    "horrorgame",
                    "puzzlegame",
                    "racinggame",
                    "simulationgame",
                    "tycoon",
                    "sandboxgame",
                    "fps",
                    "rts",
                    "tps",
                    "moba",
                    "mmo",
                    "mmorpg",
                    "battleroyale",
                ],
                MatchTags: true,
                MatchTitle: true
            ),
            new RaidKeywordRule(
                "software signal",
                35,
                [
                    "programming",
                    "softwaredev",
                    "softwaredevelopment",
                    "softwareengineer",
                    "softwareengineering",
                    "webdev",
                    "webdevelopment",
                    "coding",
                    "code",
                    "developer",
                    "backend",
                    "frontend",
                    "fullstack",
                    "fullstackdev",
                    "devops",
                    "sre",
                    "systemsprogramming",
                    "datascience",
                    "machinelearning",
                    "python",
                    "typescript",
                    "ruby",
                    "php",
                    "golang",
                    "elixir",
                    "erlang",
                    "haskell",
                    "scala",
                    "clojure",
                    "kotlin",
                    "swift",
                    "dart",
                    "flutter",
                    "elm",
                    "fsharp",
                    "ocaml",
                    "julia",
                    "perl",
                    "crystal",
                    "nim",
                    "zig",
                    "r",
                    "rlanguage",
                    "react",
                    "reactjs",
                    "vue",
                    "vuejs",
                    "angular",
                    "svelte",
                    "sveltekit",
                    "next",
                    "nextjs",
                    "nuxt",
                    "nuxtjs",
                    "astro",
                    "remix",
                    "django",
                    "flask",
                    "fastapi",
                    "rails",
                    "laravel",
                    "symfony",
                    "spring",
                    "springboot",
                    "aspnetcore",
                    "nodejs",
                    "node",
                    "deno",
                    "bun",
                    "express",
                    "expressjs",
                    "html",
                    "html5",
                    "css",
                    "css3",
                    "scss",
                    "sass",
                    "less",
                    "tailwind",
                    "tailwindcss",
                    "bootstrap",
                    "jquery",
                    "webpack",
                    "vite",
                    "postgres",
                    "postgresql",
                    "mysql",
                    "mariadb",
                    "mongodb",
                    "redis",
                    "elasticsearch",
                    "sqlite",
                    "cassandra",
                    "dynamodb",
                    "kubernetes",
                    "k8s",
                    "docker",
                    "terraform",
                    "ansible",
                    "helm",
                    "nginx",
                    "apache",
                    "aws",
                    "azure",
                    "gcp",
                    "cloudflare",
                    "digitalocean",
                    "heroku",
                    "vercel",
                    "netlify",
                    "prometheus",
                    "grafana",
                    "kafka",
                    "rabbitmq",
                    "bash",
                    "zsh",
                    "fish",
                    "powershell",
                    "emacs",
                    "neovim",
                    "vim",
                    "git",
                    "microservices",
                    "graphql",
                    "restapi",
                    "api",
                    "grpc",
                    "websockets",
                ],
                MatchTags: true,
                MatchTitle: true
            ),
        ],
        ViewerBands:
        [
            new RaidViewerBand(1, 50, 25, "small"),
            new RaidViewerBand(0, 200, 10, "mid"),
            new RaidViewerBand(0, 500, -5, "medium"),
            new RaidViewerBand(0, 1000, -15, "big"),
            new RaidViewerBand(0, 5000, -30, "large"),
            new RaidViewerBand(0, int.MaxValue, -50, "giant"),
        ],
        Recency: new RaidRecencyRules(
            NeverRaidedWeight: 30,
            Steps:
            [
                new RaidRecencyStep(7, -40, "cooldown"),
                new RaidRecencyStep(14, -15, "recent"),
                new RaidRecencyStep(30, 5, ""),
            ],
            OlderWeight: 25,
            OlderNote: "stale"
        ),
        Balance: new RaidBalanceWeights(
            OwedBaseWeight: 55,
            OwedExtraWeight: 12,
            ReciprocalWeight: 10
        ),
        FollowedWeight: 50
    );
}
